<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 *
 * @inheritdoc
 */
function hu_search_client_theme($existing, $type, $theme, $path) {

  return [
    'hu_search_client' => [
      'variables' => [
        'query' => '',
        'title' => '',
		'show_title' => false,
        'results' => [],
        'categories' => [],
        'page_info' => [],
        'display_info' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hu_search_client_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hu_search_client':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
      break;
  }

  return NULL;
}
