<?php

/**
 * @file
 * Installation functions for Howard University Search module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 *
 * Allows anonymous Drupal users to use the Howard University Search module default.
 *
 */
function hu_search_client_install() {
  user_role_change_permissions(RoleInterface::ANONYMOUS_ID, array(
    'access howard search' => true, // TODO: Change to false.
  ));
}
